# serverless.yml

service: express-app

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: us-east-1

functions:
  app:
    handler: app.handler
    events:
      - http: ANY /
      - http:
          method: ANY
          path: /{proxy+}
